/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dasgher.oe.calculator

import kotlin.test.Test
import kotlin.test.assertNotNull

class MainApplicationTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = MainApplication()
        true
    }
}
