/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dasgher.oe.calculator

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.SpringApplication

@SpringBootApplication
class MainApplication

fun main(args: Array<String>) {
  SpringApplication.run(MainApplication::class.java, *args)
}
